feat(docker-within-docker): build docker wityhin another docker container

diff --git a/{{ cookiecutter.project_slug }}/.devcontainer/Dockerfile b/{{ cookiecutter.project_slug }}/.devcontainer/Dockerfile
--- a/{{ cookiecutter.project_slug }}/.devcontainer/Dockerfile
+++ b/{{ cookiecutter.project_slug }}/.devcontainer/Dockerfile
@@ -1,25 +1,45 @@
-# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.163.1/containers/python-3/.devcontainer/base.Dockerfile
+# Note: You can use any Debian/Ubuntu based image you want. 
+FROM mcr.microsoft.com/vscode/devcontainers/base:0-buster AS base-builder
 
-# [Choice] Python version: 3, 3.9, 3.8, 3.7, 3.6
-ARG VARIANT="3"
-FROM mcr.microsoft.com/vscode/devcontainers/python:0-${VARIANT} AS builder
+# [Option] Install zsh
+ARG INSTALL_ZSH="true"
+# [Option] Upgrade OS packages to their latest versions
+ARG UPGRADE_PACKAGES="false"
+# [Option] Enable non-root Docker access in container
+ARG ENABLE_NONROOT_DOCKER="true"
+# [Option] Use the OSS Moby CLI instead of the licensed Docker CLI
+ARG USE_MOBY="true"
 
-# secerts management using chamber
-FROM segment/chamber:2.9.1 as chamber-builder
+# Install needed packages and setup non-root user. Use a separate RUN statement to add your
+# own dependencies. A user of "automatic" attempts to reuse an user ID if one already exists.
+ARG USERNAME=automatic
+ARG USER_UID=1000
+ARG USER_GID=$USER_UID
+COPY library-scripts/*.sh /tmp/library-scripts/
+RUN apt-get update \
+    && /bin/bash /tmp/library-scripts/common-debian.sh "${INSTALL_ZSH}" "${USERNAME}" "${USER_UID}" "${USER_GID}" "${UPGRADE_PACKAGES}" "true" "true" \
+    # Use Docker script from script library to set things up
+    && /bin/bash /tmp/library-scripts/docker-debian.sh "${ENABLE_NONROOT_DOCKER}" "/var/run/docker-host.sock" "/var/run/docker.sock" "${USERNAME}" "${USE_MOBY}" \
+    # Clean up
+    && apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/* /tmp/library-scripts/
 
-FROM builder
-# COPY files
+FROM base-builder
 
-COPY dotfiles /root/dotfiles
-COPY --from=chamber-builder /chamber /usr/bin/chamber
-
-# pip3 packages
-RUN set -ex \
-    && pip3 --disable-pip-version-check --no-cache-dir install pipenv ggshield pre-commit commitizen cruft
+# Setting the ENTRYPOINT to docker-init.sh will configure non-root access to 
+# the Docker socket if "overrideCommand": false is set in devcontainer.json. 
+# The script will also execute CMD if you need to alter startup behaviors.
+ENTRYPOINT [ "/usr/local/share/docker-init.sh" ]
+CMD [ "sleep", "infinity" ]
 
 # OS packages.
 RUN set -ex \
     && apt-get update && export DEBIAN_FRONTEND=noninteractive \
-    && apt-get -y install --no-install-recommends git-flow bash-completion
+    && apt-get -y install --no-install-recommends git-flow bash-completion make python3-pip
 
+# # pip3 packages
+RUN set -ex \
+    && pip3 --disable-pip-version-check --no-cache-dir install pipenv ggshield pre-commit 
 
+# To handle dependencies
+RUN set -ex \
+    && pip3 --disable-pip-version-check --no-cache-dir install cruft commitizen
